apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: talant-api4
spec:
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: talant-api4
  targetCPUUtilizationPercentage: 80
