---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: talant-api4
  name: talant-api4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talant-api4
  template:
    metadata:
      labels:
        app: talant-api4
    spec:
      containers:
      - image: ktalant/api4:v1
        name: api4
        imagePullPolicy: Always  
        resources:
          limits:
            cpu: "0.4"
          requests:
            cpu: "0.1"
      initContainers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "export HOST_IP=$(hostname -i)"] 
---
apiVersion: v1
kind: Service
metadata:
  name: talant-api4-svc
spec:
  selector:
    app: talant-api4
  ports:
    - port: 8080
      targetPort: 5000
  type: LoadBalancer
