apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: talant-loadtester
  name: talant-loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talant-loadtester
  template:
    metadata:
      labels:
        app: talant-loadtester
    spec:
      containers:
      - image: busybox
        name: busybox
        command:
          - /bin/sh
          - -c 
          - "while true; do wget -q -O- http://34.16.79.216:8080; done" 
